<!DOCTYPE html>
<!-- specifies what language is being used-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Female travelling web application">
    <meta name="author" content="Aneeka Ahmad">


    <!--Bootstrap link below this line, along with my own custom CSS styling file -->
    <!-- Bootstrap core CSS -->
    <link href="CSS/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="CSS/bootstrap-theme.css" rel="stylesheet">
    <link href="CSS/my-style.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--<link href="CSS/my-style.css" rel="stylesheet"> -->
    <title>Aneeka's project - <?php echo $view->pageTitle ?> </title>



</head>
<body role="document">

<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top  ">
    <div class="container-fluid">
        <a class="navbar-brand" href="index.php" ><img src="/Media/travel.png" alt="plane icon" /></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>

        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="index.php">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="profilepage.php">Your profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="map.php">Map feed</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="users.php">Registered Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="reviews.php">User reviews</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.php">Contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="adminpage.php">Admin</a>
                </li>
            </ul>


            <!-- <form class="d-flex" role="search"> -->

                <form class="d-flex" role="search" action="searchcontroller.php" method = "post" >
                    <input class="form-control me-2" type="text" onkeyup="liveSearch(this.value)" name="searchBox" placeholder="Search" >
                    <button class="btn btn-outline-primary" type ="submit" name="submitButton">Search...</button>
                </form>
                <!-- <p>Suggestion: <ul id ="txtHint"></ul></p> -->
            <!-- </form> -->

                <?php

                if (!isset($_SESSION["login"])) {
                    echo ' 
            <form method="post" action="" class="form text-primary">
                <label for="username">Username</label>
                <input type="text" name="username">
                <label for="password">Password</label>
                <input type="text" name="password">
                <input type="submit" name="loginbutton" value="Login">
                

            </form>';
                }
                else
                {
                    echo '
            <form method="post" action="" class="form text-primary">
                <input type="submit" name="logoutbutton" value="Logout">
            </form>';
                }
                ?>

        </div>
    </div>
</nav>
<ul id ="txtHint"></ul>





