<?php require('template/header.phtml') ?>

<div class="container d-flex justify-content-center">

    <div class="row">
        <div class="col-md-6 mx-auto">
    <form id="form" action="contact.php" method="post">
        <div class="container center-block text-center">
            <h1>Contact Form</h1>
            <p>Please fill in all fields</p>
            <hr>

            <div class="form-group">
            <label for="name"><b>Name</b></label>
            <input type="text" placeholder="Enter your name" name="name" required>
            </div>

            <div class="form-group">
            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter Email" name="email" required>
            </div>

            <div class="form-group">
            <label for="message"><b>Your Message</b></label>
                <textarea type="text" row="8" placeholder="Enter your message" name="message" required></textarea>
            </div>

        </div>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
            Send
        </button>
    </form>

</div>
</div>
</div>





    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Message has been sent
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>





<?php require('template/footer.phtml') ?>